server:
  port: 8030
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态路由的功能，利用微服务名进行路由
      routes:
        - id: product_service_route_id
          uri: lb://EUREKA-PRODUCT-SERVICE
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/